language: minimal

services:
  - docker

cache:
  directories:
    - cache/docker_images

before_install:
  - gunzip -c cache/docker_images/images.tar.gz | docker load || true

script:
  - docker build -t 1tgr/websocket-lite . && docker-compose up --exit-code-from test

before_cache:
  - rm cache/docker_images/*
  - docker save $(docker images -a -q) | gzip -c > cache/docker_images/images.tar.gz
